doc-warnings: yes
test-warnings: yes
max-line-length: 1000 # It's probably just me but I don't give a flying crap about how long lines are
ignore-paths:
    - taskstack-database
    - taskstack/manage.py
ignore-patterns:
    # All these Django files shouldn't need documentation or linting because
    # they are the same for every Django project/app
    - wsgi.py
    - urls.py
    - models.py
    - views.py
    - admin.py
    - __init__.py
