language: python
python:
    - "3.4"
addons:
    postgresql: "9.3"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libpq-dev
    - pip install -r requirements.txt

env:
    - POSTGRES_DB="127.0.0.1" POSTGRES_USER="postgres" POSTGRES_PASSWORD="postgres"

before_script:
    - psql -c 'create database taskstack;' -U postgres
    - python3 taskstack/manage.py migrate

script:
    - python3 taskstack/manage.py test taskstack
# Test!
