#!/bin/bash

export TASKSTACK_POSTGRES_HOST=${DB_PORT_5432_TCP_ADDR}
export TASKSTACK_POSTGRES_PORT=${DB_PORT_5432_TCP_PORT}
export TASKSTACK_POSTGRES_DATABASE=${DB_ENV_POSTGRES_USER:-'postgres'}
export TASKSTACK_POSTGRES_USER=${DB_ENV_POSTGRES_USER:-'postgres'}
export TASKSTACK_POSTGRES_PASSWORD=${DB_ENV_POSTGRES_PASSWORD}

python manage.py migrate

gunicorn --bind 0.0.0.0:8000 taskstack.wsgi
